[package]
name = "luarus-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "luarus"
path = "src/main.rs"

[dependencies]
luarus-syntax.workspace = true
luarus-bytecode.workspace = true
luarus-compile.workspace = true
luarus-gen.workspace = true
luarus-interp.workspace = true
luarus-vm.workspace = true
